
<!-- This .Rmd file is set up to run either independently by checking for 
the presence of necessary objects in the global environment and running 
related scripts if not, or also as a child to the "main-doc". For that latter
reason, comments and headings that are not relevant to a final report to
pubic audiences are suppressed or moved to code chunks that can optionally be 
`echo`ed as desired. -->

```{r run scripts for necessary packages and objects as necessary}
if (!"chHexs"        %in% objects()) source("settings--main.R", echo = FALSE)
if (!"my_state_abbr" %in% objects()) source("settings--profile.R", echo = FALSE)
if (!"bin_age"       %in% objects()) source("method--general-helper-functions.R", echo = FALSE)
```

<!-- # Prepare All Data ------------------------------------------------------->

```{r identify relevant fips codes}
my_state_fip <- 
  fips_codes %>% 
  filter(state == my_state_abbr) %>% 
  pull(state_code) %>% 
  unique()

if ("my_county" %in% objects()) {
  my_county_fip <- 
    fips_codes %>% 
    filter(state == my_state_abbr, 
           str_detect(county, my_county)) %>% 
    pull(county_code) %>% 
    unique() 
}
```


<!-- ## Load Geographic Data -------------------------------------------------->

<!-- ### Load Geographic Crosswalks ------------------------------------------->

```{r prepare ACS 5-year crosswalk data}
geo_crosswalk_puma <-
  fread("https://www2.census.gov/geo/docs/maps-data/data/rel/2010_Census_Tract_to_2010_PUMA.txt") %>% 
    # for reference, this is the 2020 tract-to-PUMA crosswalk. While ACS5 data
    # from 2020 is available and uses this, the ACS1 data pull from 2021 uses
    # 2010 PUMA definitions. Temporarily, we are planning to continue to work on
    # a 2010 basis by pulling ACS5 data from 2019
    # "https://www2.census.gov/geo/docs/maps-data/data/rel2020/2020_Census_Tract_to_2020_PUMA.txt"
  .[STATEFP == my_state_fip] %>% 
  # /!\ Am not aware of the significance of the FIP versus CE suffix. It's an 
  # assumption that there's no consequence to dropping the distinction
  rename(STATEFIP = STATEFP, 
         TRACTFIP = TRACTCE,
         PUMA     = PUMA5CE) %>% 
  mutate(STATEFIP  = str_pad(STATEFIP, width = 2, side = "left", pad = "0"),
         TRACTFIP  = str_pad(TRACTFIP, width = 6, side = "left", pad = "0"),
         COUNTYFIP = str_pad(COUNTYFP, width = 3, side = "left", pad = "0"),
         GEOID = paste0(STATEFIP, COUNTYFIP, TRACTFIP))

geo_crosswalk_zcta <-
  fread("https://www2.census.gov/geo/docs/maps-data/data/rel/zcta_tract_rel_10.txt") %>%
  .[STATE == my_state_fip] %>% 
  .[j = GEOID := as.character(GEOID)]
  # Will be able to update this for 2020 at: https://www2.census.gov/geo/docs/maps-data/data/rel2020/zcta520/

geo_crosswalk <-
  merge(geo_crosswalk_puma,
        geo_crosswalk_zcta %>% select(GEOID, ZCTA = ZCTA5),
        by = "GEOID",
        all.x = TRUE) %>% 
  data.table()

if (exists("my_county_fip")) {
  geo_crosswalk <- geo_crosswalk[COUNTYFIP == my_county_fip]
}
```

<!-- ### Pull Shapefiles if Necessary ----------------------------------------->

```{r auto pull of tract and puma shapefiles}

# Declare which vintage of Census TIGER shapefiles should be pulled
tiger_year <- 2019

# Set up input to tigris functions for pulling by county
# Note that because the "else" value is NULL, the ifelse() has a problem
if (exists("my_county_fip")) county_val <- my_county_fip else county_val <- NULL

# Note that cb = TRUE requests a lower-res file, which is fine for mapping we want to do

tractShp  <-   tracts(state = my_state_fip, cb = TRUE, year = tiger_year, county = county_val)
pumaShp   <-    pumas(state = my_state_fip, cb = TRUE, year = tiger_year) 
countyShp <- counties(state = my_state_fip, cb = TRUE, year = tiger_year)
zctaShp   <-    zctas(cb = TRUE, year = tiger_year, starts_with = zcta_starts)
  # Note: we pull zctas differently--with "starts_with" rather than state because
  # the zctas() function can only return by state for years 2000 and 2010 
```

```{r rename certain fields in shapefiles to agree with those in the crosswalks}
countyShp <-
  countyShp %>% 
  rename(COUNTYFIP = COUNTYFP,
         County = NAME)

zctaShp <-
  zctaShp %>% 
  rename(ZCTA = ZCTA5CE10)
```


```{r add county name to geo_crosswalk help label estimates}
geo_crosswalk <- 
  geo_crosswalk %>% 
  merge(countyShp %>% as.data.frame() %>% transmute(COUNTYFP = as.integer(COUNTYFIP), County = County) %>% unique(),
        by = "COUNTYFP",
        all.x = TRUE)
```


```{r load and feed in any auxiliary geographies}

if (exists("my_aux_geo")) {
  
  # Read in auxiliary data shape
  auxShp <- st_read(my_aux_geo)
  
  # Give a generic name to the aux geography's label field
  auxShp$aux_geo_label <- auxShp %>% pull(get(my_aux_geo_field))

  # Reproject if necessary
  if (st_crs(auxShp) != st_crs(tractShp)) {
    auxShp <- 
      st_transform(auxShp,
                   crs = st_crs(tractShp))
  }
  
  # Attempt to identify intersections
  tract_aux_intersection <- st_intersection(tractShp,
                                            auxShp)
    # This returns all geographies of tract sliced by aux, i.e. 
    # representing potential duplicates
  sf_use_s2(FALSE)
    # This above step is recommended to avoid findings of degenerate geometries due
    # to duplicate vertices: https://github.com/r-spatial/sf/issues/1762
  
  tract_aux_intersection$area <- st_area(tract_aux_intersection)
  
  # Examine duplicates to see whether any existing duplicates 
  if (FALSE) {
    tract_aux_intersection %>% 
      group_by(GEOID) %>% 
      filter(n() > 1) %>% 
      select(GEOID, aux_geo_label, area) %>% 
      arrange(GEOID) %>% 
      View()
  }
  
  # Plot overlap to examine any potential issues
  if (FALSE) {
    ggplot() +
      geom_sf(data = auxShp %>% filter(str_detect(NAME, "District 299")),
              color = "green", 
              fill = NA, 
              linewidth = 1) + 
      geom_sf(data = tractShp %>% filter(COUNTYFP == "031"), 
              color = "red",   
              fill = NA) +
      theme_void()
  }
  
  # Subset intersected geographies to those with areas that are within 2 orders of
  # magnitude of the largest. This is primarily to rule out idiosyncratic overlaps
  tract_aux_intersection_pcts <- 
    tract_aux_intersection  %>%
    group_by(GEOID) %>% 
    mutate(pct_area = as.numeric(area) / sum(as.numeric(area)))
  
  # Examine the histogram of prorations
  if (FALSE) {
    ggplot(tract_aux_intersection_pcts %>% filter(str_detect(NAME.1, "District 299"))) + 
      geom_histogram(aes(x = pct_area))
  }
  
  geo_crosswalk_aux <- 
    tract_aux_intersection_pcts %>% 
    filter(pct_area > 0.01)
    # /!\ Non-trivial overlaps need to be investigated -- in some practice cases
    # we've seen overlaps of over 20% where we expected trivial overlaps at best
    # suggesting that there's something more than just projection issues.
    # %>% filter(pct_area > 0.50)
  #stopifnot(any(table(tract_aux_intersection_keep$GEOID) > 1) == FALSE)
}
```

```{r examine plots of the geographies}
# /!\ Need to generalize this
leaflet_base_map <- 
  leaflet() %>% # width = "100%"
  addProviderTiles("CartoDB.Positron") %>%
  addPolygons(group = "Tracts",
              data = tractShp, 
              color = "black", #"#050505",
              weight = 1.0, 
              fillOpacity = 0.0) %>%
  addPolygons(group = "PUMAs",
              data = pumaShp,
              popup = ~GEOID10,
              color = "red",
              weight = 3.0, 
              fillOpacity = 0.0)

if (exists("my_aux_geo")) {
  leaflet_base_map <- 
    leaflet_base_map %>% 
    addPolygons(group = my_aux_geo_desc,
                data = auxShp,
                popup = ~aux_geo_label,
                color = "green",
                weight = 5.0,
                fillOpacity = 0.0)
}
  
leaflet_base_map %>% 
  addLayersControl(
    # baseGroups = c(),
    overlayGroups = c("Tracts", 
                      "PUMAs", 
                      my_aux_geo_desc),
    options = layersControlOptions(collapsed = FALSE))
```


```{r collect and save GIS data}
geo_objects <- c("my_state_fip", "geo_crosswalk", "geo_crosswalk_zcta", "tractShp", "pumaShp", "countyShp", "zctaShp", "leaflet_base_map")
if (exists("auxShp")) geo_objects <- c(geo_objects, "auxShp", "geo_crosswalk_aux")
if (exists("my_county_fip")) geo_objects <- c(geo_objects, "my_county_fip")

```


```{r save applicable GIS objects}
save(list = geo_objects,
     file = glue("{output_path}geo_data_{my_output_tag}.Rda"))
```
